### ISSUE TITLE
Wrong tweet name

### ISSUE THREAD

**Issue by tribet84** [wasbazi/speed-and-tweet#2]
When posting the tweet is not using the user name value:

> λ speed-and-tweet -r plusnethelp -i 20 -t 10
> running test
> speed 0.28 Mb/s
> url undefined
> TWEETING NOW:  @**undefined** I pay for plusnethelpMb/s and only get 0.28 Mb/s. undefined #YourTry github.com/wasbazi/speed-and-tweet
> Tweet successful

**Comment by tribet84** [comment]
> λ speed-and-tweet -i 20 -t 10
> running test
> speed 0.31 Mb/s
> url undefined
> TWEETING NOW:  @**undefined** I pay for comcastMb/s and only get 0.31 Mb/s. undefined #YourTry github.com/wasbazi/speed-and-tweet
> Tweet successful

**Comment by tribet84** [comment]
You have a PR :)

**Comment by wasbazi** [comment]
Fixed by #5
